### ISSUE TITLE
HeaderComponent

### ISSUE THREAD

**Issue by maxdhn** [WildCodeSchool/tours-projet2-nej#35]
- Menu non fonctionnel sur mobile

Déclencher 
```typescript
this.service.get().subscribe(
      (param) => {
        this.name = param.firstName;
      });
```
seulement si l'utilisateur est connecté, car sinon ça provoque une erreur 401 dans la console du navigateur. Utiliser la méthode `isLogin` pour savoir si l'utilisateur est connecte (voir issue #36 )

**Comment by nicomoro** [comment]
corrigé
